# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20170405_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
    ]
